name: Run Discord Bot

on:
  schedule:
    - cron: '17 13 * * *'

jobs:
  run-bot:
    runs-on: fedora-latest #or windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python wulfing.py